version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_naimix
    restart: always
    ports:
      - '${POSTGRES_PORT:-7100}:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: deploy/docker/back.Dockerfile
    container_name: naimix-api
    ports:
      - 7000:7000
    depends_on:
      - postgres

volumes:
  postgres_data: