# Generated by Django 5.1.3 on 2024-11-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet", models.CharField(max_length=50)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TRINE", "Trigon"),
                            ("SQUARE", "Square"),
                            ("CONJUNCTION", "Conjunction"),
                            ("OPPOSITION", "Opposition"),
                            ("SEXTILE", "Sextile"),
                            ("QUINCUNX", "Quincunx"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orb", models.FloatField()),
                (
                    "planet1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect1",
                        to="horoscope.planetposition",
                    ),
                ),
                (
                    "planet2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect2",
                        to="horoscope.planetposition",
                    ),
                ),
            ],
        ),
    ]
